//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoyaltySurvey.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoyaltySurvey.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BackgroundCallBack {
            get {
                object obj = ResourceManager.GetObject("BackgroundCallBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BackgroundClinicRecommend {
            get {
                object obj = ResourceManager.GetObject("BackgroundClinicRecommend", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BackgroundComment {
            get {
                object obj = ResourceManager.GetObject("BackgroundComment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BackgroundError {
            get {
                object obj = ResourceManager.GetObject("BackgroundError", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BackgroundThanks {
            get {
                object obj = ResourceManager.GetObject("BackgroundThanks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BottomLineContinuesClear {
            get {
                object obj = ResourceManager.GetObject("BottomLineContinuesClear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BottomLineTemplate {
            get {
                object obj = ResourceManager.GetObject("BottomLineTemplate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonBack {
            get {
                object obj = ResourceManager.GetObject("ButtonBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonBackspace {
            get {
                object obj = ResourceManager.GetObject("ButtonBackspace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonCapslock {
            get {
                object obj = ResourceManager.GetObject("ButtonCapslock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonClear {
            get {
                object obj = ResourceManager.GetObject("ButtonClear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonClose {
            get {
                object obj = ResourceManager.GetObject("ButtonClose", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonDown {
            get {
                object obj = ResourceManager.GetObject("ButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonLeft {
            get {
                object obj = ResourceManager.GetObject("ButtonLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonOk {
            get {
                object obj = ResourceManager.GetObject("ButtonOk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonRight {
            get {
                object obj = ResourceManager.GetObject("ButtonRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonSearch {
            get {
                object obj = ResourceManager.GetObject("ButtonSearch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonShiftPressed {
            get {
                object obj = ResourceManager.GetObject("ButtonShiftPressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonShiftUnpressed {
            get {
                object obj = ResourceManager.GetObject("ButtonShiftUnpressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonUp {
            get {
                object obj = ResourceManager.GetObject("ButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ClinicRate0 {
            get {
                object obj = ResourceManager.GetObject("ClinicRate0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ClinicRate10 {
            get {
                object obj = ResourceManager.GetObject("ClinicRate10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ClinicRate5 {
            get {
                object obj = ResourceManager.GetObject("ClinicRate5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DepartmentWithoutAPhoto {
            get {
                object obj = ResourceManager.GetObject("DepartmentWithoutAPhoto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DoctorRate1 {
            get {
                object obj = ResourceManager.GetObject("DoctorRate1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DoctorRate2 {
            get {
                object obj = ResourceManager.GetObject("DoctorRate2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DoctorRate3 {
            get {
                object obj = ResourceManager.GetObject("DoctorRate3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DoctorRate4 {
            get {
                object obj = ResourceManager.GetObject("DoctorRate4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DoctorRate5 {
            get {
                object obj = ResourceManager.GetObject("DoctorRate5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DoctorWithoutAPhoto {
            get {
                object obj = ResourceManager.GetObject("DoctorWithoutAPhoto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LogoBzFull {
            get {
                object obj = ResourceManager.GetObject("LogoBzFull", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LogoBzSmall {
            get {
                object obj = ResourceManager.GetObject("LogoBzSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Можно мы позвоним Вам, чтобы узнать подробности?.
        /// </summary>
        internal static string StringPageCallbackQuestion {
            get {
                return ResourceManager.GetString("StringPageCallbackQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для выбора коснитесь нужной кнопки.
        /// </summary>
        internal static string StringPageCallbackSubtitle {
            get {
                return ResourceManager.GetString("StringPageCallbackSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для ввода используйте экранную клавиатуру.
        /// </summary>
        internal static string StringPageCallbackSubtitleTextBox {
            get {
                return ResourceManager.GetString("StringPageCallbackSubtitleTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уважаемый пациент!.
        /// </summary>
        internal static string StringPageCallbackTitle {
            get {
                return ResourceManager.GetString("StringPageCallbackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите свой номер телефона, чтобы мы смогли Вам перезвонить.
        /// </summary>
        internal static string StringPageCallbackTitleTextBox {
            get {
                return ResourceManager.GetString("StringPageCallbackTitleTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не знаю.
        /// </summary>
        internal static string StringPageClinicRateDontKnow {
            get {
                return ResourceManager.GetString("StringPageClinicRateDontKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Буду рекомендовать.
        /// </summary>
        internal static string StringPageClinicRateMostLikely {
            get {
                return ResourceManager.GetString("StringPageClinicRateMostLikely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Однозначно нет.
        /// </summary>
        internal static string StringPageClinicRateNotAtAll {
            get {
                return ResourceManager.GetString("StringPageClinicRateNotAtAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для выбора коснитесь кнопки с нужной оценкой.
        /// </summary>
        internal static string StringPageClinicRateSubtitle {
            get {
                return ResourceManager.GetString("StringPageClinicRateSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста, оцените по десятибалльной шкале
        ///насколько бы Вы порекомендовали нашу клинику своим друзьям и знакомым?.
        /// </summary>
        internal static string StringPageClinicRateTitle {
            get {
                return ResourceManager.GetString("StringPageClinicRateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Желаете ли Вы оставить комментарий?.
        /// </summary>
        internal static string StringPageCommentQuestion {
            get {
                return ResourceManager.GetString("StringPageCommentQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для выбора коснитесь нужной кнопки.
        /// </summary>
        internal static string StringPageCommentSubtitle {
            get {
                return ResourceManager.GetString("StringPageCommentSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для ввода используйте экранную клавиатуру.
        /// </summary>
        internal static string StringPageCommentSubtitleTextBox {
            get {
                return ResourceManager.GetString("StringPageCommentSubtitleTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уважаемый пациент!.
        /// </summary>
        internal static string StringPageCommentTitle {
            get {
                return ResourceManager.GetString("StringPageCommentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Напишите свой комментарий.
        /// </summary>
        internal static string StringPageCommentTitleTextBox {
            get {
                return ResourceManager.GetString("StringPageCommentTitleTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Найти врача по фамилии.
        /// </summary>
        internal static string StringPageDepartmentSelectSearchButton {
            get {
                return ResourceManager.GetString("StringPageDepartmentSelectSearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для выбора коснитесь нужной кнопки.
        /// </summary>
        internal static string StringPageDepartmentSelectSubtitle {
            get {
                return ResourceManager.GetString("StringPageDepartmentSelectSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Найдите врача по фамилии или выберите отделение, в котором Вы были.
        /// </summary>
        internal static string StringPageDepartmentSelectTitle {
            get {
                return ResourceManager.GetString("StringPageDepartmentSelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для выбора коснитесь кнопки с нужной оценкой.
        /// </summary>
        internal static string StringPageDoctorRateSubtitle {
            get {
                return ResourceManager.GetString("StringPageDoctorRateSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста, оцените качество приема у врача.
        /// </summary>
        internal static string StringPageDoctorRateTitle {
            get {
                return ResourceManager.GetString("StringPageDoctorRateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начните вводить фамилию врача.
        /// </summary>
        internal static string StringPageDoctorSearchInitial {
            get {
                return ResourceManager.GetString("StringPageDoctorSearchInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на К сожалению, ничего не найдено
        ///Попробуйте изменить строку поиска.
        /// </summary>
        internal static string StringPageDoctorSearchNothingFound {
            get {
                return ResourceManager.GetString("StringPageDoctorSearchNothingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для ввода используйте экранную клавиатуру.
        /// </summary>
        internal static string StringPageDoctorSearchSubtitleEmpty {
            get {
                return ResourceManager.GetString("StringPageDoctorSearchSubtitleEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для выбора коснитесь кнопки с врачом.
        /// </summary>
        internal static string StringPageDoctorSearchSubtitleFound {
            get {
                return ResourceManager.GetString("StringPageDoctorSearchSubtitleFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск врача по фамилии.
        /// </summary>
        internal static string StringPageDoctorSearchTitle {
            get {
                return ResourceManager.GetString("StringPageDoctorSearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для выбора коснитесь кнопки с врачом.
        /// </summary>
        internal static string StringPageDoctorSelectSubtitle {
            get {
                return ResourceManager.GetString("StringPageDoctorSelectSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите врача, у которого Вы были на приеме.
        /// </summary>
        internal static string StringPageDoctorSelectTitle {
            get {
                return ResourceManager.GetString("StringPageDoctorSelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на К сожалению, сервис временно недоступен
        ///по техническим причинам..
        /// </summary>
        internal static string StringPageErrorMessage {
            get {
                return ResourceManager.GetString("StringPageErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приносим свои извинения за доставленные неудобства. Администрация..
        /// </summary>
        internal static string StringPageErrorSubtitle {
            get {
                return ResourceManager.GetString("StringPageErrorSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уважаемые пациенты!.
        /// </summary>
        internal static string StringPageErrorTitle {
            get {
                return ResourceManager.GetString("StringPageErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для продолжения коснитесь экрана.
        /// </summary>
        internal static string StringPageSplashScreenSubtitle {
            get {
                return ResourceManager.GetString("StringPageSplashScreenSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Просим Вас уделить пару минут и оценить качество нашей работы.
        /// </summary>
        internal static string StringPageSplashScreenTitleLeftBottom {
            get {
                return ResourceManager.GetString("StringPageSplashScreenTitleLeftBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на МЫ СТРЕМИМСЯ СТАТЬ.
        /// </summary>
        internal static string StringPageSplashScreenTitleLeftTop {
            get {
                return ResourceManager.GetString("StringPageSplashScreenTitleLeftTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЛУЧШЕ.
        /// </summary>
        internal static string StringPageSplashScreenTitleRight {
            get {
                return ResourceManager.GetString("StringPageSplashScreenTitleRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Просим Вас принять участие в опросе о качестве работы нашей клиники.
        /// </summary>
        internal static string StringPageSplashScreenWelcome {
            get {
                return ResourceManager.GetString("StringPageSplashScreenWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для продолжения коснитесь экрана.
        /// </summary>
        internal static string StringPageThanksSubtitle {
            get {
                return ResourceManager.GetString("StringPageThanksSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на за участие в нашем опросе!.
        /// </summary>
        internal static string StringPageThanksTitleLeftBottom {
            get {
                return ResourceManager.GetString("StringPageThanksTitleLeftBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на МЫ ЦЕНИМ ВАШЕ МНЕНИЕ.
        /// </summary>
        internal static string StringPageThanksTitleLeftRight {
            get {
                return ResourceManager.GetString("StringPageThanksTitleLeftRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на БЛАГОДАРИМ ВАС.
        /// </summary>
        internal static string StringPageThanksTitleLeftTop {
            get {
                return ResourceManager.GetString("StringPageThanksTitleLeftTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очень плохо.
        /// </summary>
        internal static string StringRateDoctorMark1 {
            get {
                return ResourceManager.GetString("StringRateDoctorMark1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Плохо.
        /// </summary>
        internal static string StringRateDoctorMark2 {
            get {
                return ResourceManager.GetString("StringRateDoctorMark2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Средне.
        /// </summary>
        internal static string StringRateDoctorMark3 {
            get {
                return ResourceManager.GetString("StringRateDoctorMark3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хорошо.
        /// </summary>
        internal static string StringRateDoctorMark4 {
            get {
                return ResourceManager.GetString("StringRateDoctorMark4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отлично.
        /// </summary>
        internal static string StringRateDoctorMark5 {
            get {
                return ResourceManager.GetString("StringRateDoctorMark5", resourceCulture);
            }
        }
    }
}
