//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoyaltySurvey.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoyaltySurvey.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BackButton2 {
            get {
                object obj = ResourceManager.GetObject("BackButton2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Background_CallBack {
            get {
                object obj = ResourceManager.GetObject("Background_CallBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Background_Comment {
            get {
                object obj = ResourceManager.GetObject("Background_Comment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BottomLineContinuesClear {
            get {
                object obj = ResourceManager.GetObject("BottomLineContinuesClear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BottomLineTemplate {
            get {
                object obj = ResourceManager.GetObject("BottomLineTemplate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButterflyClear {
            get {
                object obj = ResourceManager.GetObject("ButterflyClear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonBackspace {
            get {
                object obj = ResourceManager.GetObject("ButtonBackspace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonCapslock {
            get {
                object obj = ResourceManager.GetObject("ButtonCapslock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonClear {
            get {
                object obj = ResourceManager.GetObject("ButtonClear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonClose {
            get {
                object obj = ResourceManager.GetObject("ButtonClose", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonLeft {
            get {
                object obj = ResourceManager.GetObject("ButtonLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonOk {
            get {
                object obj = ResourceManager.GetObject("ButtonOk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonRight {
            get {
                object obj = ResourceManager.GetObject("ButtonRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonSearch {
            get {
                object obj = ResourceManager.GetObject("ButtonSearch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonShiftPressed {
            get {
                object obj = ResourceManager.GetObject("ButtonShiftPressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonShiftUnpressed {
            get {
                object obj = ResourceManager.GetObject("ButtonShiftUnpressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DownButton {
            get {
                object obj = ResourceManager.GetObject("DownButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_dislike {
            get {
                object obj = ResourceManager.GetObject("icon_dislike", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_dont_know {
            get {
                object obj = ResourceManager.GetObject("icon_dont_know", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_like {
            get {
                object obj = ResourceManager.GetObject("icon_like", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Recommend {
            get {
                object obj = ResourceManager.GetObject("Recommend", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap smile_angry {
            get {
                object obj = ResourceManager.GetObject("smile_angry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap smile_happy {
            get {
                object obj = ResourceManager.GetObject("smile_happy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap smile_love {
            get {
                object obj = ResourceManager.GetObject("smile_love", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap smile_neutral {
            get {
                object obj = ResourceManager.GetObject("smile_neutral", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap smile_sad {
            get {
                object obj = ResourceManager.GetObject("smile_sad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Можно мы позвоним Вам, чтобы узнать подробности?.
        /// </summary>
        internal static string StringPageCallbackQuestion {
            get {
                return ResourceManager.GetString("StringPageCallbackQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для выбора коснитесь нужной кнопки.
        /// </summary>
        internal static string StringPageCallbackSubtitle {
            get {
                return ResourceManager.GetString("StringPageCallbackSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для ввода используйте экранную клавиатуру.
        /// </summary>
        internal static string StringPageCallbackSubtitleTextBox {
            get {
                return ResourceManager.GetString("StringPageCallbackSubtitleTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уважаемый пациент!.
        /// </summary>
        internal static string StringPageCallbackTitle {
            get {
                return ResourceManager.GetString("StringPageCallbackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите свой номер телефона, чтобы мы смогли Вам перезвонить.
        /// </summary>
        internal static string StringPageCallbackTitleTextBox {
            get {
                return ResourceManager.GetString("StringPageCallbackTitleTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не знаю.
        /// </summary>
        internal static string StringPageClinicRateDontKnow {
            get {
                return ResourceManager.GetString("StringPageClinicRateDontKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Буду рекомендовать.
        /// </summary>
        internal static string StringPageClinicRateMostLikely {
            get {
                return ResourceManager.GetString("StringPageClinicRateMostLikely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Однозначно нет.
        /// </summary>
        internal static string StringPageClinicRateNotAtAll {
            get {
                return ResourceManager.GetString("StringPageClinicRateNotAtAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста,
        ///оцените по десятибальной шкале насколько бы Вы порекомендовали
        ///нашу клинику своим друзьям и знакомым?.
        /// </summary>
        internal static string StringPageClinicRateQuestion {
            get {
                return ResourceManager.GetString("StringPageClinicRateQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для выбора коснитесь нужной кнопки.
        /// </summary>
        internal static string StringPageClinicRateSubtitle {
            get {
                return ResourceManager.GetString("StringPageClinicRateSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на И последний вопрос.
        /// </summary>
        internal static string StringPageClinicRateTitle {
            get {
                return ResourceManager.GetString("StringPageClinicRateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Желаете ли Вы оставить комментарий?.
        /// </summary>
        internal static string StringPageCommentQuestion {
            get {
                return ResourceManager.GetString("StringPageCommentQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для выбора коснитесь нужной кнопки.
        /// </summary>
        internal static string StringPageCommentSubtitle {
            get {
                return ResourceManager.GetString("StringPageCommentSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для ввода используйте экранную клавиатуру.
        /// </summary>
        internal static string StringPageCommentSubtitleTextBox {
            get {
                return ResourceManager.GetString("StringPageCommentSubtitleTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уважаемый пациент!.
        /// </summary>
        internal static string StringPageCommentTitle {
            get {
                return ResourceManager.GetString("StringPageCommentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Напишите свой комментарий.
        /// </summary>
        internal static string StringPageCommentTitleTextBox {
            get {
                return ResourceManager.GetString("StringPageCommentTitleTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Найти врача по фамилии.
        /// </summary>
        internal static string StringPageDepartmentSelectSearchButton {
            get {
                return ResourceManager.GetString("StringPageDepartmentSelectSearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для выбора коснитесь нужной кнопки.
        /// </summary>
        internal static string StringPageDepartmentSelectSubtitle {
            get {
                return ResourceManager.GetString("StringPageDepartmentSelectSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Найдите врача по фамилии или выберите отделение, в котором Вы были.
        /// </summary>
        internal static string StringPageDepartmentSelectTitle {
            get {
                return ResourceManager.GetString("StringPageDepartmentSelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для выбора коснитесь кнопки с нужной оценкой.
        /// </summary>
        internal static string StringPageDoctorRateSubtitle {
            get {
                return ResourceManager.GetString("StringPageDoctorRateSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста, оцените качество приема у врача.
        /// </summary>
        internal static string StringPageDoctorRateTitle {
            get {
                return ResourceManager.GetString("StringPageDoctorRateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начните вводить фамилию врача.
        /// </summary>
        internal static string StringPageDoctorSearchInitial {
            get {
                return ResourceManager.GetString("StringPageDoctorSearchInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на К сожалению, ничего не найдено
        ///Попробуйте изменить строку поиска.
        /// </summary>
        internal static string StringPageDoctorSearchNothingFound {
            get {
                return ResourceManager.GetString("StringPageDoctorSearchNothingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для ввода используйте экранную клавиатуру.
        /// </summary>
        internal static string StringPageDoctorSearchSubtitleEmpty {
            get {
                return ResourceManager.GetString("StringPageDoctorSearchSubtitleEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для выбора коснитесь кнопки с врачом.
        /// </summary>
        internal static string StringPageDoctorSearchSubtitleFound {
            get {
                return ResourceManager.GetString("StringPageDoctorSearchSubtitleFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск врача по фамилии.
        /// </summary>
        internal static string StringPageDoctorSearchTitle {
            get {
                return ResourceManager.GetString("StringPageDoctorSearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для выбора коснитесь кнопки с врачом.
        /// </summary>
        internal static string StringPageDoctorSelectSubtitle {
            get {
                return ResourceManager.GetString("StringPageDoctorSelectSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите врача у которого Вы были на приеме.
        /// </summary>
        internal static string StringPageDoctorSelectTitle {
            get {
                return ResourceManager.GetString("StringPageDoctorSelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на К сожалению, cервис временно недоступен.
        /// </summary>
        internal static string StringPageErrorSubtitle {
            get {
                return ResourceManager.GetString("StringPageErrorSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уважаемые пациенты!.
        /// </summary>
        internal static string StringPageErrorTitle {
            get {
                return ResourceManager.GetString("StringPageErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для продолжения коснитесь экрана.
        /// </summary>
        internal static string StringPageSplashScreenSubtitle {
            get {
                return ResourceManager.GetString("StringPageSplashScreenSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Помогите нам стать лучше!.
        /// </summary>
        internal static string StringPageSplashScreenTitle {
            get {
                return ResourceManager.GetString("StringPageSplashScreenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Просим Вас принять участие в опросе о качестве работы нашей клиники.
        /// </summary>
        internal static string StringPageSplashScreenWelcome {
            get {
                return ResourceManager.GetString("StringPageSplashScreenWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваше мнение очень важно для нас!.
        /// </summary>
        internal static string StringPageThanksSubtitle {
            get {
                return ResourceManager.GetString("StringPageThanksSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Благодарим Вас за участие в опросе.
        /// </summary>
        internal static string StringPageThanksTitle {
            get {
                return ResourceManager.GetString("StringPageThanksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очень плохо.
        /// </summary>
        internal static string StringRateDoctorMark1 {
            get {
                return ResourceManager.GetString("StringRateDoctorMark1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Плохо.
        /// </summary>
        internal static string StringRateDoctorMark2 {
            get {
                return ResourceManager.GetString("StringRateDoctorMark2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Средне.
        /// </summary>
        internal static string StringRateDoctorMark3 {
            get {
                return ResourceManager.GetString("StringRateDoctorMark3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хорошо.
        /// </summary>
        internal static string StringRateDoctorMark4 {
            get {
                return ResourceManager.GetString("StringRateDoctorMark4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отлично.
        /// </summary>
        internal static string StringRateDoctorMark5 {
            get {
                return ResourceManager.GetString("StringRateDoctorMark5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap thanks_1 {
            get {
                object obj = ResourceManager.GetObject("thanks_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap thanks_2 {
            get {
                object obj = ResourceManager.GetObject("thanks_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UnknownDepartment {
            get {
                object obj = ResourceManager.GetObject("UnknownDepartment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UnknownDoctor {
            get {
                object obj = ResourceManager.GetObject("UnknownDoctor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UpButton {
            get {
                object obj = ResourceManager.GetObject("UpButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
