//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoyaltySurvey.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoyaltySurvey.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BackgroundCallBack {
            get {
                object obj = ResourceManager.GetObject("BackgroundCallBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BackgroundClinicRecommend {
            get {
                object obj = ResourceManager.GetObject("BackgroundClinicRecommend", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BackgroundComment {
            get {
                object obj = ResourceManager.GetObject("BackgroundComment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BackgroundError {
            get {
                object obj = ResourceManager.GetObject("BackgroundError", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BackgroundThanks {
            get {
                object obj = ResourceManager.GetObject("BackgroundThanks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BottomLineContinuesClear {
            get {
                object obj = ResourceManager.GetObject("BottomLineContinuesClear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BottomLineTemplate {
            get {
                object obj = ResourceManager.GetObject("BottomLineTemplate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonBack {
            get {
                object obj = ResourceManager.GetObject("ButtonBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonBackspace {
            get {
                object obj = ResourceManager.GetObject("ButtonBackspace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonCapslock {
            get {
                object obj = ResourceManager.GetObject("ButtonCapslock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonClear {
            get {
                object obj = ResourceManager.GetObject("ButtonClear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonClose {
            get {
                object obj = ResourceManager.GetObject("ButtonClose", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonDown {
            get {
                object obj = ResourceManager.GetObject("ButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonLeft {
            get {
                object obj = ResourceManager.GetObject("ButtonLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonOk {
            get {
                object obj = ResourceManager.GetObject("ButtonOk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonRight {
            get {
                object obj = ResourceManager.GetObject("ButtonRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonSearch {
            get {
                object obj = ResourceManager.GetObject("ButtonSearch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonShiftPressed {
            get {
                object obj = ResourceManager.GetObject("ButtonShiftPressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonShiftUnpressed {
            get {
                object obj = ResourceManager.GetObject("ButtonShiftUnpressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonUp {
            get {
                object obj = ResourceManager.GetObject("ButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ClinicRate0 {
            get {
                object obj = ResourceManager.GetObject("ClinicRate0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ClinicRate10 {
            get {
                object obj = ResourceManager.GetObject("ClinicRate10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ClinicRate5 {
            get {
                object obj = ResourceManager.GetObject("ClinicRate5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DepartmentWithoutAPhoto {
            get {
                object obj = ResourceManager.GetObject("DepartmentWithoutAPhoto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DoctorRate1 {
            get {
                object obj = ResourceManager.GetObject("DoctorRate1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DoctorRate2 {
            get {
                object obj = ResourceManager.GetObject("DoctorRate2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DoctorRate3 {
            get {
                object obj = ResourceManager.GetObject("DoctorRate3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DoctorRate4 {
            get {
                object obj = ResourceManager.GetObject("DoctorRate4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DoctorRate5 {
            get {
                object obj = ResourceManager.GetObject("DoctorRate5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Doctors {
            get {
                object obj = ResourceManager.GetObject("Doctors", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DoctorWithoutAPhoto {
            get {
                object obj = ResourceManager.GetObject("DoctorWithoutAPhoto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LogoBzFull {
            get {
                object obj = ResourceManager.GetObject("LogoBzFull", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LogoBzSmall {
            get {
                object obj = ResourceManager.GetObject("LogoBzSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NewYearSnowflakes {
            get {
                object obj = ResourceManager.GetObject("NewYearSnowflakes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NewYearTinsel {
            get {
                object obj = ResourceManager.GetObject("NewYearTinsel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NewYearTree {
            get {
                object obj = ResourceManager.GetObject("NewYearTree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicRegistry {
            get {
                object obj = ResourceManager.GetObject("PicRegistry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Можно мы позвоним Вам, чтобы узнать подробности?.
        /// </summary>
        internal static string StringPageCallbackQuestion {
            get {
                return ResourceManager.GetString("StringPageCallbackQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для выбора коснитесь нужной кнопки.
        /// </summary>
        internal static string StringPageCallbackSubtitle {
            get {
                return ResourceManager.GetString("StringPageCallbackSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для ввода используйте экранную клавиатуру.
        /// </summary>
        internal static string StringPageCallbackSubtitleTextBox {
            get {
                return ResourceManager.GetString("StringPageCallbackSubtitleTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уважаемый пациент!.
        /// </summary>
        internal static string StringPageCallbackTitle {
            get {
                return ResourceManager.GetString("StringPageCallbackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите свой номер телефона, чтобы мы смогли Вам перезвонить.
        /// </summary>
        internal static string StringPageCallbackTitleTextBox {
            get {
                return ResourceManager.GetString("StringPageCallbackTitleTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не знаю.
        /// </summary>
        internal static string StringPageClinicRateDontKnow {
            get {
                return ResourceManager.GetString("StringPageClinicRateDontKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Буду рекомендовать.
        /// </summary>
        internal static string StringPageClinicRateMostLikely {
            get {
                return ResourceManager.GetString("StringPageClinicRateMostLikely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Однозначно нет.
        /// </summary>
        internal static string StringPageClinicRateNotAtAll {
            get {
                return ResourceManager.GetString("StringPageClinicRateNotAtAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для выбора коснитесь кнопки с нужной оценкой.
        /// </summary>
        internal static string StringPageClinicRateSubtitle {
            get {
                return ResourceManager.GetString("StringPageClinicRateSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, оцените по десятибалльной шкале
        ///насколько бы Вы порекомендовали нашу клинику своим друзьям и знакомым?.
        /// </summary>
        internal static string StringPageClinicRateTitle {
            get {
                return ResourceManager.GetString("StringPageClinicRateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Желаете ли Вы оставить комментарий?.
        /// </summary>
        internal static string StringPageCommentQuestion {
            get {
                return ResourceManager.GetString("StringPageCommentQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для выбора коснитесь нужной кнопки.
        /// </summary>
        internal static string StringPageCommentSubtitle {
            get {
                return ResourceManager.GetString("StringPageCommentSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для ввода используйте экранную клавиатуру.
        /// </summary>
        internal static string StringPageCommentSubtitleTextBox {
            get {
                return ResourceManager.GetString("StringPageCommentSubtitleTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уважаемый пациент!.
        /// </summary>
        internal static string StringPageCommentTitle {
            get {
                return ResourceManager.GetString("StringPageCommentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Напишите свой комментарий.
        /// </summary>
        internal static string StringPageCommentTitleTextBox {
            get {
                return ResourceManager.GetString("StringPageCommentTitleTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск врача по фамилии.
        /// </summary>
        internal static string StringPageDepartmentSelectSearchButton {
            get {
                return ResourceManager.GetString("StringPageDepartmentSelectSearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для выбора коснитесь нужной кнопки.
        /// </summary>
        internal static string StringPageDepartmentSelectSubtitle {
            get {
                return ResourceManager.GetString("StringPageDepartmentSelectSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите отделение, в котором Вы были или найдите врача по фамилии.
        /// </summary>
        internal static string StringPageDepartmentSelectTitle {
            get {
                return ResourceManager.GetString("StringPageDepartmentSelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для выбора коснитесь кнопки с нужной оценкой.
        /// </summary>
        internal static string StringPageDoctorRateSubtitle {
            get {
                return ResourceManager.GetString("StringPageDoctorRateSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, оцените прием у врача.
        /// </summary>
        internal static string StringPageDoctorRateTitle {
            get {
                return ResourceManager.GetString("StringPageDoctorRateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начните вводить фамилию врача.
        /// </summary>
        internal static string StringPageDoctorSearchInitial {
            get {
                return ResourceManager.GetString("StringPageDoctorSearchInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to К сожалению, ничего не найдено
        ///Попробуйте изменить строку поиска.
        /// </summary>
        internal static string StringPageDoctorSearchNothingFound {
            get {
                return ResourceManager.GetString("StringPageDoctorSearchNothingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для ввода используйте экранную клавиатуру.
        /// </summary>
        internal static string StringPageDoctorSearchSubtitleEmpty {
            get {
                return ResourceManager.GetString("StringPageDoctorSearchSubtitleEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для выбора коснитесь кнопки с врачом.
        /// </summary>
        internal static string StringPageDoctorSearchSubtitleFound {
            get {
                return ResourceManager.GetString("StringPageDoctorSearchSubtitleFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск врача по фамилии.
        /// </summary>
        internal static string StringPageDoctorSearchTitle {
            get {
                return ResourceManager.GetString("StringPageDoctorSearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для выбора коснитесь кнопки с врачом.
        /// </summary>
        internal static string StringPageDoctorSelectSubtitle {
            get {
                return ResourceManager.GetString("StringPageDoctorSelectSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите врача, у которого Вы были на приеме.
        /// </summary>
        internal static string StringPageDoctorSelectTitle {
            get {
                return ResourceManager.GetString("StringPageDoctorSelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to К сожалению, сервис временно недоступен
        ///по техническим причинам..
        /// </summary>
        internal static string StringPageErrorMessage {
            get {
                return ResourceManager.GetString("StringPageErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приносим свои извинения за доставленные неудобства. Администрация..
        /// </summary>
        internal static string StringPageErrorSubtitle {
            get {
                return ResourceManager.GetString("StringPageErrorSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уважаемые пациенты!.
        /// </summary>
        internal static string StringPageErrorTitle {
            get {
                return ResourceManager.GetString("StringPageErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для выбора коснитесь кнопки с нужной оценкой.
        /// </summary>
        internal static string StringPageRegistryRateSubitle {
            get {
                return ResourceManager.GetString("StringPageRegistryRateSubitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, оцените работу регистратуры.
        /// </summary>
        internal static string StringPageRegistryRateTitle {
            get {
                return ResourceManager.GetString("StringPageRegistryRateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оценка приема у врача.
        /// </summary>
        internal static string StringPageSelectSurveyDoctorsRate {
            get {
                return ResourceManager.GetString("StringPageSelectSurveyDoctorsRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оценка работы регистратуры.
        /// </summary>
        internal static string StringPageSelectSurveyRegistryRate {
            get {
                return ResourceManager.GetString("StringPageSelectSurveyRegistryRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для выбора коснитесь нужной кнопки.
        /// </summary>
        internal static string StringPageSelectSurveySubtitle {
            get {
                return ResourceManager.GetString("StringPageSelectSurveySubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите опрос.
        /// </summary>
        internal static string StringPageSelectSurveyTitle {
            get {
                return ResourceManager.GetString("StringPageSelectSurveyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для продолжения коснитесь экрана.
        /// </summary>
        internal static string StringPageSplashScreenSubtitle {
            get {
                return ResourceManager.GetString("StringPageSplashScreenSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просим Вас уделить пару минут и оценить нашу работу.
        /// </summary>
        internal static string StringPageSplashScreenTitleLeftBottom {
            get {
                return ResourceManager.GetString("StringPageSplashScreenTitleLeftBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to МЫ СТРЕМИМСЯ СТАТЬ.
        /// </summary>
        internal static string StringPageSplashScreenTitleLeftTop {
            get {
                return ResourceManager.GetString("StringPageSplashScreenTitleLeftTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЛУЧШЕ.
        /// </summary>
        internal static string StringPageSplashScreenTitleRight {
            get {
                return ResourceManager.GetString("StringPageSplashScreenTitleRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просим Вас принять участие в опросе о работе нашей клиники.
        /// </summary>
        internal static string StringPageSplashScreenWelcome {
            get {
                return ResourceManager.GetString("StringPageSplashScreenWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для продолжения коснитесь экрана.
        /// </summary>
        internal static string StringPageThanksSubtitle {
            get {
                return ResourceManager.GetString("StringPageThanksSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to за участие в нашем опросе!.
        /// </summary>
        internal static string StringPageThanksTitleLeftBottom {
            get {
                return ResourceManager.GetString("StringPageThanksTitleLeftBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to МЫ ЦЕНИМ ВАШЕ МНЕНИЕ.
        /// </summary>
        internal static string StringPageThanksTitleLeftRight {
            get {
                return ResourceManager.GetString("StringPageThanksTitleLeftRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to БЛАГОДАРИМ ВАС.
        /// </summary>
        internal static string StringPageThanksTitleLeftTop {
            get {
                return ResourceManager.GetString("StringPageThanksTitleLeftTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очень плохо.
        /// </summary>
        internal static string StringRateDoctorMark1 {
            get {
                return ResourceManager.GetString("StringRateDoctorMark1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Плохо.
        /// </summary>
        internal static string StringRateDoctorMark2 {
            get {
                return ResourceManager.GetString("StringRateDoctorMark2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Средне.
        /// </summary>
        internal static string StringRateDoctorMark3 {
            get {
                return ResourceManager.GetString("StringRateDoctorMark3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хорошо.
        /// </summary>
        internal static string StringRateDoctorMark4 {
            get {
                return ResourceManager.GetString("StringRateDoctorMark4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отлично.
        /// </summary>
        internal static string StringRateDoctorMark5 {
            get {
                return ResourceManager.GetString("StringRateDoctorMark5", resourceCulture);
            }
        }
    }
}
